name: Test on instaui tag trigger

on:
  repository_dispatch:
    types: [instaui_tagged]


env:
  NPM_DIR_NAME: npm-src

jobs:
  testing:
    name: testing web app
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.0-focal
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4

      - name: set up python and uv
        uses: instaui-python/org-ci-config/.github/actions/python-env@main

      - name: set up npm-src and testing
        uses: instaui-python/org-ci-config/.github/actions/npm-env@main
        with:
          npm_dir_name : ${{ env.NPM_DIR_NAME }}

      - name: Install the project
        run: uv sync --dev
        shell: bash

      - name: run tests
        timeout-minutes: 1
        run: |
          uv run pytest __tests
        shell: bash